/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author dnyyy
 */
public class StorageElement extends javax.swing.JPanel {
    private Cart cart;
    private Wishlist whishlist;
    /**
     * Creates new form ShopProductElement
     * @param cart
     * @param whishlist
     */
    public StorageElement(Cart cart, Wishlist whishlist) {
        initComponents();
        this.cart = cart;
        this.whishlist = whishlist;
    }
    public StorageElement(int id, String name, int price, String category, int available) {
        productPanel.setLabelsByParameters(id, name, price, category, available);
    }

    public void setLabels(String product[]) {
        productPanel.setLabelsByArray(product);
    }
    
    public void setLabels(int id, String name, int price, String category, int available) {
        productPanel.setLabelsByParameters(id, name, price, category, available);
    }
    
    public onlineshop.Product getProductPanel() {
        return productPanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productPanel = new onlineshop.Product();
        cartButton = new javax.swing.JButton();
        whishlistButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        setMaximumSize(new java.awt.Dimension(32767, 31));
        setSize(new java.awt.Dimension(622, 31));

        cartButton.setText("Kosarhoz");
        cartButton.setFocusable(false);
        cartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartButtonMouseClicked(evt);
            }
        });
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        whishlistButton.setText("Whishlist");
        whishlistButton.setFocusable(false);
        whishlistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whishlistButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(productPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(whishlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartButton)
                    .addComponent(whishlistButton))
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartButtonActionPerformed

    private void cartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartButtonMouseClicked
        try {
            if (cart.quantityVerification(this.productPanel) || this.productPanel.getAvailable() == 0) {
                throw new Exception("A kivalasztott termekbol nincs tobb.");
            }
            cart.addToCart(productPanel);
        } catch (Exception e) {
            throwError(e, "Keszlethiany", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cartButtonMouseClicked

    private void whishlistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whishlistButtonMouseClicked
        try {
            if (whishlist.find(this.getProductPanel())) {
                throw new Exception("Ezt az elemet mar hozzaadta a listahoz!");
            } 
            whishlist.addToWishlist(productPanel);
        } catch (Exception e) {
            throwError(e, "Ismetlodesi hiba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_whishlistButtonMouseClicked

    private void throwError(Exception e, String errorTitle, int messageType) {
        JOptionPane optionPane = new JOptionPane(e.getMessage(), messageType);
        JDialog dialog = optionPane.createDialog(errorTitle);
        dialog.setLocationByPlatform(true);
        dialog.setLocationRelativeTo(this);
        dialog.setAlwaysOnTop(true); // to show top of all other application
        dialog.setVisible(true); // to visible the dialog
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartButton;
    private onlineshop.Product productPanel;
    private javax.swing.JButton whishlistButton;
    // End of variables declaration//GEN-END:variables
}
