/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author dnyyy
 */
public class Table extends javax.swing.JPanel {
    // variables:
    protected MainWindow main;
    // these are for setting the right sizes
    protected final int height = 31;
    protected final int minWidth = 622;
    protected final int margin = 4;
    /**
     * Creates new from StoragePanel
     */
    //
    // constructor:
    public Table() {
        initComponents();
        Scroll.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    // setter for main variable (sometimes we have to access to main (e.g. total output))
    public void setMain(MainWindow main) {
        this.main = main;
    }
    
    // prepare for a new element
    public void addRowSettings(int listSize) {
        if (listSize == 1) {
            productContainer.setPreferredSize(new Dimension(this.getPreferredSize().width, productContainer.getPreferredSize().height + 12));
        }
        
        if (this.getSize().width < minWidth) {
            productContainer.setPreferredSize(new Dimension(minWidth, productContainer.getPreferredSize().height + height + margin));
            productContainer.setSize(minWidth, productContainer.getPreferredSize().height + height + margin);
        } else {
            productContainer.setPreferredSize(new Dimension(Scroll.getPreferredSize().width - 25, productContainer.getPreferredSize().height + height + margin));
            productContainer.setSize(this.getSize().width - 25, this.getSize().height + height + margin);
        }
    }
    
    // add the appropiate element to Table
    public void addWishlistElement(WishlistElement element) {
        productContainer.add(element);
    }
    public void addStorageElement(StorageElement element) {
        productContainer.add(element);
    }
    public void addCartElement(CartElement element) {
        productContainer.add(element);
    }
    
    // throws JOptionPane by the given exception
    public void throwMessage(Exception e, String errorTitle, int messageType) {
        JOptionPane optionPane = new JOptionPane(e.getMessage(), messageType);
        JDialog dialog = optionPane.createDialog(errorTitle);
        dialog.setLocationByPlatform(true);
        dialog.setLocationRelativeTo(this);
        dialog.setAlwaysOnTop(true); // to show top of all other application
        dialog.setVisible(true); // to visible the dialog
    }
    
    // remove all element from table and set its value for basic
    public void resetTable() {
        productContainer.removeAll();
        productContainer.repaint();
        productContainer.setPreferredSize(new Dimension(0, 0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();
        productContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        setMinimumSize(new java.awt.Dimension(622, 200));
        setPreferredSize(new java.awt.Dimension(622, 200));
        setSize(new java.awt.Dimension(622, 200));

        Scroll.setBorder(null);
        Scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        productContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout productContainerLayout = new javax.swing.GroupLayout(productContainer);
        productContainer.setLayout(productContainerLayout);
        productContainerLayout.setHorizontalGroup(
            productContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productContainerLayout.setVerticalGroup(
            productContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Scroll.setViewportView(productContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JPanel productContainer;
    // End of variables declaration//GEN-END:variables
}
