/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author dnyyy
 */
public class testPanelContainer extends javax.swing.JPanel {

    /**
     * Creates new form testPanelContainer
     */
    private List<onlineshop.TestPanel> testPanels;
    
    public testPanelContainer() {
        testPanels = new ArrayList();
        initComponents();
//        testPanel2.setVisible(false);
//        String menu[] = {"123", "123", "asd", "jkl", "321"};
//        
//        addRow(menu);
    }

    public void addRow(String rowLabels[]) {
        testPanels.add(new onlineshop.TestPanel());
        getLastPanel().setLabels(rowLabels);
        getLastPanel().setLocation(0, getPenultPanel().getY() + 30);
//        getLastPanel().setSize(new Dimension());
        this.add(getLastPanel());
        getLastPanel().setVisible(true);
        
    }

    private onlineshop.TestPanel getLastPanel() {
        return testPanels.get(testPanels.size() - 1);
    }
    
    private onlineshop.TestPanel getPenultPanel() {
        if (testPanels.size() > 1) {
            return testPanels.get(testPanels.size() - 2);
        } else {
            return testPanels.get(testPanels.size() - 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testPanel2 = new onlineshop.TestPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(testPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private onlineshop.TestPanel testPanel2;
    // End of variables declaration//GEN-END:variables
}
