/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineshop;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author dnyyy
 */
public class testPanelContainer extends javax.swing.JPanel {

    /**
     * Creates new form testPanelContainer
     */
    private final List<onlineshop.ShopProductElement> testPanels;
    
    public testPanelContainer() {
        testPanels = new ArrayList();
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
//        testPanel2.setVisible(false);
//        String menu[] = {"123", "123", "asd", "jkl", "321"};
//        
//        addRow(menu);
    }

    public void addRow(String rowLabels[]) {
        testPanels.add(new onlineshop.ShopProductElement());
        getLastPanel().setLabels(rowLabels);
        
        if (testPanels.size() == 1) {
            getLastPanel().setLocation(0, 6);
            container.setPreferredSize(new Dimension(this.getPreferredSize().width, container.getPreferredSize().height + 12));
        } else {
            getLastPanel().setLocation(0, getPenultPanel().getY() + 31);
        }
        
        
        if (this.getSize().width < 622) {
            container.setPreferredSize(new Dimension(622, container.getPreferredSize().height + 31));
            container.setSize(622, container.getPreferredSize().height + 31);
            getLastPanel().setSize(622, 31);
        } else {
            container.setPreferredSize(new Dimension(jScrollPane1.getPreferredSize().width - 20, container.getPreferredSize().height + 31));
            container.setSize(jScrollPane1.getPreferredSize().width - 20, container.getPreferredSize().height + 31);
            getLastPanel().setSize(this.getSize().width - 20, 31);
        }
        
        container.add(getLastPanel());
        getLastPanel().setVisible(true);
        
    }

    private onlineshop.ShopProductElement getLastPanel() {
        return testPanels.get(testPanels.size() - 1);
    }
    
    private onlineshop.ShopProductElement getPenultPanel() {
        if (testPanels.size() > 1) {
            return testPanels.get(testPanels.size() - 2);
        } else {
            return testPanels.get(testPanels.size() - 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(622, 200));
        setPreferredSize(new java.awt.Dimension(622, 200));
        setSize(new java.awt.Dimension(622, 200));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setSize(new java.awt.Dimension(0, 0));

        container.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
